#https://goreleaser.com/static/schema.json

# docker run -it --rm -v $PWD:/app -v /app:/app -w /app -e GOPROXY=https://goproxy.cn registry.cn-qingdao.aliyuncs.com/bjdgyc/gocross goreleaser build --skip=validate --clean --debug

version: 1

dist: dist

before:
  hooks:
    - pwd
    - go mod tidy
    - go generate ./...

builds:
  - id: "build"
    #main: .
    dir: ./server
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-linux-gnu-gcc {{- end }}
          {{- if eq .Arch "arm64" }}CC=aarch64-linux-gnu-gcc {{- end }}
        {{- end }}
        {{- if eq .Os "darwin" }}
          {{- if eq .Arch "amd64"}}CC=o64-clang{{- end }}
          {{- if eq .Arch "arm64"}}CC=oa64-clang{{- end }}
        {{- end }}
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64"}}CC=x86_64-w64-mingw32-gcc{{- end }}
          {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
        {{- end }}
    goos:
      - linux
      #- darwin
      #- windows
    goarch:
      - amd64
      - arm64
    command: build
    flags: -trimpath
    ldflags:
      - "-s -w -extldflags '-static'" -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=dcross

archives:
  - id: "archive1"
    format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
