name: release-tag-version

on:
  push:
    branches:
      - 'main'
    tags:
      - "v0.*"
      - "v1.*"

jobs:
  Build:
    name: build-binary
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bjdgyc
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: set env
        run: |
          appVer=`cat version`
          commit=`git rev-parse HEAD`
          echo "APP_VER=$appVer" >> $GITHUB_ENV
          echo "COMMIT=$commit" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: Commit=${{ env.COMMIT }},Ver=${{ env.APP_VER }}
          tags: bjdgyc/dcross:latest,bjdgyc/dcross:${{ env.APP_VER }}
