name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [ ubuntu-latest, linux-arm64 ]
    env:
      TZ: Asia/Shanghai
    steps:
      - run: |
          echo "Hello world!"
          uname -a