name: test

on:
  workflow_dispatch:

#  release:
#    types:
#      - created
#
#- name: Uploading assets...
#    id: upload-release-asset
#    uses: actions/upload-release-asset@v1
#    env:
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#    with:
#      upload_url: ${{ github.event.release.upload_url }}
#      asset_path: ./kubectl-karmada-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
#      asset_name: kubectl-karmada-${{ matrix.goos }}-${{ matrix.goarch }}.tgz
#      asset_content_type: application/gzip
# ${{ github.ref }}

jobs:
  test:
    #linux-arm64 docker pull golang:1.20-bookworm
    runs-on: [ ubuntu-latest ]
    env:
      TZ: Asia/Shanghai
    steps:
      - run: |
          echo "Hello world!"
          uname -a
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: mytest
        run: |
          go env
          echo "################"
          env
          sudo apt-get install -y -q gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
