name: test

on:
  workflow_dispatch:

jobs:
  test:
    #linux-arm64
    runs-on: [ ubuntu-latest ]
    env:
      TZ: Asia/Shanghai
    steps:
      - run: |
          echo "Hello world!"
          uname -a